<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>d71e678e-9d4b-4249-9f77-412e7e01ca0f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
    <PackageReference Include="Aspire.Hosting.Azure.CosmosDB" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mammapuls.Api\Mammapuls.Api.csproj" />
  </ItemGroup>

</Project>
